version: '3.7'
services:
  mysql:
    restart: always
    image: mariadb:10.4
    command: ['mysqld','--character-set-server=utf8']
    ports:
    - 3306:3306
    volumes:
      - databasevolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
  openemr:
    restart: always
    #image: openemr/openemr:5.0.2
    build: ../openemr-devops/docker/openemr/flex-3.10
    ports:
      - 8300:80
      - 9000:443
    volumes:
    - .:/openemr:ro
    - .:/var/www/localhost/htdocs/openemr:rw
    - publicvolume:/var/www/localhost/htdocs/openemr/public:rw
    - sitesvolume:/var/www/localhost/htdocs/openemr/sites/default:rw
    - nodemodules:/var/www/localhost/htdocs/openemr/node_modules:rw
    - vendordir:/var/www/localhost/htdocs/openemr/vendor:rw
    - ccdamodule:/var/www/localhost/htdocs/openemr/ccdaservice:rw
    - logvolume:/var/log
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASS: root
      MYSQL_USER: openemr
      MYSQL_PASS: openemr
      OE_USER: admin
      OE_PASS: pass
      FLEX_REPOSITORY: https://github.com/boxlady/openemr.git
      FLEX_REPOSITORY_BRANCH: "wordpress_pt"
      EASY_DEV_MODE: "yes"
      EASY_DEV_MODE_NEW: "yes"
    depends_on:
      - mysql
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
    - 8310:80
    - 9010:433
    environment:
      PMA_HOSTS: mysql
  wordpress:
    depends_on:
     - mysql
    restart: always
    image: wordpress:latest
    ports:
    - 8330:443
    - 9030:443
    volumes:
    - wordpress_files:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
volumes:
  databasevolume: {}
  publicvolume: {}
  sitesvolume: {}
  nodemodules: {}
  vendordir: {}
  ccdamodule: {}
  logvolume: {}
  wordpress_files: {}
