version: '3.7'
services:
  mysql:
    restart: always
    image: mariadb:10.4
    command: ['mysqld','--character-set-server=utf8']
    volumes:
      - databasevolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  openemr:
    restart: always
    #image: openemr/openemr:5.0.2
    build: ../openemr-devops/docker/openemr/gepdnl-5.0.2
    ports:
      - 80:80
      - 443:443
    volumes:
      - logvolume01:/var/log
      - sitevolume:/var/www/localhost/htdocs/openemr/sites
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASS: root
      MYSQL_USER: openemr
      MYSQL_PASS: openemr
      OE_USER: admin
      OE_PASS: pass
      #DOMAIN: "gepd.nl"
    depends_on:
      - mysql
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
    - 8310:80
    environment:
      PMA_HOSTS: mysql
volumes:
  logvolume01: {}
  sitevolume: {}
  databasevolume: {}